// QuizQuest RPG - Enhanced AI with 6 features. Vanilla JS. 3-char vars.
(()=>{'use strict';
let key='',sub='Mat',dif=1,ctx='',dm=0,tot=0,crt=0,stg=0,win=0,seq=0,acs=new Set(),tes=0,cch=new Map();
let plr={nm:'Hero',lvl:1,hp:100,mh:100,atk:12,def:2,xp:0,gld:0,str:0},mon={nm:'Goblin',typ:'gob',lvl:1,hp:30,mh:30,atk:6,def:1},qst={q:'',opt:[],ans:0,exp:''};
let mic={gob:'👹',orc:'👺',trl:'🐾',drg:'🐉',slm:'🧪',glm:'🤖',wth:'👻',hdr:'🐲',bnd:'🧙',knt:'⚔️',wlk:'🧙‍♂️',emp:'👑',imp:'👿',yet:'❄️',gry:'🦅',ttn:'🗿'};
const $=q=>document.querySelector(q),$$=q=>document.querySelectorAll(q),rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,cls=(e,c,o)=>o?e.classList.add(c):e.classList.remove(c),bar=(h,m)=>Math.max(0,Math.min(100,Math.round(h*100/m)))+'%',fhp=(h,m)=>`${Math.max(0,h)}/${m}`,sav=()=>localStorage.setItem('qqrpg',JSON.stringify({plr,sub,dif})),lod=()=>{try{let s=localStorage.getItem('qqrpg');if(s){let o=JSON.parse(s);plr=o.plr||plr;sub=o.sub||sub;dif=o.dif||dif}}catch(e){}};
const el={men:$('#scrMenu'),lod:$('#scrLoad'),bat:$('#scrBat'),key:$('#inpKey'),clr:$('#btnClr'),dem:$('#chkDemo'),dng:$$('.dng'),go:$('#btnStart'),pnm:$('#plrNm'),plv:$('#plrLv'),php:$('#plrHp'),pht:$('#plrHpT'),pat:$('#plrAtk'),pdf:$('#plrDef'),pst:$('#plrStr'),pxp:$('#plrXp'),pgd:$('#plrGld'),mnm:$('#monNm'),mlv:$('#monLv'),mhp:$('#monHp'),mht:$('#monHpT'),mat:$('#monAtk'),mdf:$('#monDef'),mic:$('#monIco'),nar:$('#nar'),qp:$('#qp'),opt:$('#opt'),nxt:$('#btnNxt'),log:$('#log'),ach:$('#ach')};
const msg=t=>{let d=document.createElement('div');d.className='it';d.textContent=t;el.log.prepend(d)},sys=t=>{let d=document.createElement('div');d.className='it sys';d.textContent=t;el.log.prepend(d)};
lod();
async function aic(ins,mt=300,tmp=.9,cid=''){if(!key||dm)throw Error('AI off');if(cid&&cch.has(cid))return cch.get(cid);if(!tes){try{let t=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${key}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:'Hi'}]}],generationConfig:{maxOutputTokens:5}})});tes=t.ok?1:0;if(!tes)throw Error('Test fail')}catch(e){sys('⚠️ AI unavailable - Demo mode');dm=1;throw e}}let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${key}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:ins}]}],generationConfig:{maxOutputTokens:mt,temperature:tmp,topP:.95,topK:40}})});if(!r.ok){if(r.status===429){sys('⚠️ Rate limit - waiting...');await new Promise(r=>setTimeout(r,2000));return aic(ins,mt,tmp,cid)}throw Error('AI err '+r.status)}let j=await r.json(),txt=(j.candidates?.[0]?.content?.parts?.[0]?.text)||'';if(cid&&txt)cch.set(cid,txt);if(cch.size>50)cch.clear();return txt}
async function gq(){try{let dlv=['Very Easy','Easy','Medium','Hard','Very Hard','Expert','Master','Insane'][Math.min(dif-1,7)];let prm=`You are an educational quiz generator. Create ONE ${sub} question at ${dlv} difficulty (level ${dif}/8).\n\nRequirements:\n- Question must be clear, educational, ${dif>3?'challenging and test deep understanding':'appropriate for beginners'}\n- Exactly 4 options (A-D)\n- Only ONE correct answer\n- Detailed explanation\n\nReturn ONLY this JSON (no markdown, no backticks):\n{"q":"question text","opt":["A","B","C","D"],"ans":0,"exp":"why correct answer is right"}\n\nans must be index 0-3 of correct option.`;let t=await aic(prm,450,.8),s=t.replace(/```json|```/g,'').trim(),j;try{j=JSON.parse(s)}catch(e){let m=s.match(/\{[\s\S]*?\}/);if(m)try{j=JSON.parse(m[0])}catch(e2){}}if(!j?.q||!Array.isArray(j.opt)||j.opt.length!==4||typeof j.ans!=='number'||j.ans<0||j.ans>3)throw Error('Invalid JSON');return j}catch(e){sys('⚠️ AI Q fail, local fallback');return lq()}}
async function nar(evt){try{let prm=`Write 2-3 vivid, atmospheric, encouraging sentences for:\n\nScene: ${sub} dungeon - ${evt}\nDifficulty: Level ${dif}\nMonster: ${mon.nm}\n\nMake it immersive, dramatic, and motivating. Keep under 100 words.`;let cid=`nar_${sub}_${evt}_${mon.typ}`;return(await aic(prm,200,.95,cid)).trim()}catch(e){return nfb(evt)}}
async function tnt(stt){try{let pty={gob:'sneaky and mocking',orc:'brutal and savage',trl:'slow but menacing',drg:'proud and disdainful',slm:'oozing and gross',glm:'mechanical and cold',wth:'eerie and haunting',hdr:'multi-headed chaos',bnd:'cunning thief',knt:'honorable warrior',wlk:'dark magic user',emp:'commanding ruler',imp:'devilish trickster',yet:'frozen fury',gry:'aerial predator',ttn:'ancient giant'}[mon.typ]||'fierce';let prm=`${mon.nm} (${pty}) taunts player. Situation: ${stt}. One dramatic line, max 12 words. Be menacing and in-character.`;let cid=`tnt_${mon.typ}_${stt}`;return(await aic(prm,80,1.2,cid)).trim()}catch(e){return tfb(stt)}}
async function ach(ev){try{let ctx={lvl:`player leveled up to ${plr.lvl}`,str5:'5 correct answers streak',hot:'3 correct streak',boss:`defeated ${mon.nm} boss`,win:`first monster victory`}[ev]||ev;let prm=`Create fun achievement for: ${ctx}.\n\nReturn ONLY JSON:\n{"nm":"🎯 Title with emoji","ds":"exciting description"}\n\nBe creative, use relevant emoji, keep concise.`;let t=await aic(prm,150,1.1),s=t.replace(/```json|```/g,'').trim(),j;try{j=JSON.parse(s)}catch(e){let m=s.match(/\{[\s\S]*?\}/);if(m)try{j=JSON.parse(m[0])}catch(e2){}}if(!j?.nm||!j.ds)throw 0;return j}catch(e){return acb(ev)}}
function lq(){if(sub==='Mat'){let a=rnd(2,20),b=rnd(2,20),op=['+','-','×','÷'][rnd(0,3)],ans=op==='+'?a+b:op==='-'?a-b:op==='×'?a*b:Math.floor(a/b),opt=[ans];while(opt.length<4){let d=ans+rnd(-10,10);if(d!==ans&&d>=-50&&d<=400&&!opt.includes(d))opt.push(d)}opt.sort(()=>Math.random()-.5);return{q:`${a} ${op} ${b} = ?`,opt:opt.map(String),ans:opt.indexOf(ans),exp:`${a} ${op} ${b} = ${ans}`}}let qs=sub==='Sci'?[{q:'What force pulls objects toward Earth?',opt:['Friction','Magnetism','Gravity','Inertia'],ans:2,exp:'Gravity is the force.'},{q:'H2O is the formula for?',opt:['Oxygen','Hydrogen','Salt','Water'],ans:3,exp:'H2O is water.'},{q:'The Earth orbits the…',opt:['Moon','Sun','Mars','Polaris'],ans:1,exp:'Earth orbits the Sun.'}]:sub==='His'?[{q:'Who was the first US president?',opt:['Lincoln','Jefferson','Washington','Adams'],ans:2,exp:'George Washington.'},{q:'The pyramids are in…',opt:['Rome','Giza','Babylon','Machu Picchu'],ans:1,exp:'Giza, Egypt.'},{q:'The Renaissance began in…',opt:['France','Italy','Spain','Germany'],ans:1,exp:'Italian city-states.'}]:[{q:'Capital of Japan?',opt:['Seoul','Kyoto','Tokyo','Osaka'],ans:2,exp:'Tokyo is capital.'},{q:'Largest ocean?',opt:['Indian','Atlantic','Pacific','Arctic'],ans:2,exp:'The Pacific.'},{q:'Mount Everest lies in…',opt:['Andes','Himalayas','Alps','Rockies'],ans:1,exp:'Himalayas.'}];return qs[rnd(0,qs.length-1)]}
function nfb(e){return{entry:`You step into the ${sub} halls. Torches flicker.`,spawn:`A ${mon.nm} emerges. The air tenses.`,win:`The foe fades to dust.`,lose:`Darkness edges in as you fall.`}[e]||'The dungeon stirs.'}
function tfb(s){return s==='wrong'?'Ha! Your wits are dull.':s==='monLow'?'No... I will not fall!':s==='plrLow'?'Kneel, learner!':'Grrr...'}
function acb(e){return{lvl:{nm:'🔺 Level Up!',ds:'Your power grows.'},str5:{nm:'🔥 Streak Five',ds:'Five in a row!'},hot:{nm:'🔥 On Fire!',ds:'Three in a row!'},boss:{nm:'🐉 Dragon Tamer',ds:'You felled the dragon!'},win:{nm:'🏆 First Victory',ds:'Your first triumph!'}}[e]||{nm:'✨ Milestone',ds:'A feat.'}}
function rst(){plr.hp=plr.mh;plr.str=tot=crt=stg=win=0;dif=1;seq++;if(el.log)el.log.innerHTML='';if(el.ach)el.ach.innerHTML='';acs.clear();upd()}
function adp(){if(tot>0){let w=crt/tot,old=dif,reason='';if(plr.str>=5&&dif<8){dif++;reason='Hot streak!'}else if(tot%5===0){if(w>.85&&dif<8){dif+=2;reason='Too easy'}else if(w>.7&&dif<8){dif++;reason='Mastery'}else if(w<.45&&dif>1){dif--;reason='Struggling'}else reason='Stable'}if(old!==dif){sys(`📊 AI Adaptive: Lv${old}→${dif} (${(w*100).toFixed(0)}% accuracy - ${reason})`)}}}
const pdm=()=>Math.round(plr.atk*(1+plr.str*.1)),mdm=()=>Math.max(1,mon.atk-plr.def),msc=b=>Math.round(b*(1+(plr.lvl-1)*.3));
function lvc(){let lv=Math.floor(Math.sqrt(plr.xp/100))+1;if(lv>plr.lvl){let g=lv-plr.lvl;plr.lvl=lv;plr.mh+=20*g;plr.atk+=5*g;plr.def+=2*g;plr.hp=plr.mh;sys(`Level ${lv}! +${20*g}HP +${5*g}ATK +${2*g}DEF`);bdg('lvl')}}
function spn(){let lst={Mat:[['Goblin','gob',30,6,1],['Orc','orc',50,9,2],['Troll','trl',80,12,3],['Dragon','drg',150,18,5]],Sci:[['Slime','slm',28,5,1],['Golem','glm',55,9,2],['Wraith','wth',85,12,3],['Hydra','hdr',140,17,4]],His:[['Bandit','bnd',32,6,1],['Knight','knt',58,10,2],['Warlock','wlk',88,13,3],['Emperor','emp',160,19,5]],Geo:[['Imp','imp',26,5,1],['Yeti','yet',52,9,2],['Gryphon','gry',90,13,3],['Titan','ttn',155,19,5]]}[sub],b=lst[stg%4];mon={nm:b[0],typ:b[1],lvl:plr.lvl,hp:msc(b[2]),mh:msc(b[2]),atk:msc(b[3]),def:b[4]};if(el.mic)el.mic.textContent=mic[mon.typ]||'👹';upd();$('#monBox').classList.remove('bad');setTimeout(()=>$('#monBox').classList.add('bad'),50)}
function upd(){el.pnm.textContent=plr.nm;el.plv.textContent='Lv '+plr.lvl;el.php.style.width=bar(plr.hp,plr.mh);el.pht.textContent=fhp(plr.hp,plr.mh);el.pat.textContent=plr.atk;el.pdf.textContent=plr.def;el.pst.textContent=plr.str;el.pxp.textContent=plr.xp;el.pgd.textContent=plr.gld;el.mnm.textContent=mon.nm;el.mlv.textContent='Lv '+mon.lvl;el.mhp.style.width=bar(mon.hp,mon.mh);el.mht.textContent=fhp(mon.hp,mon.mh);el.mat.textContent=mon.atk;el.mdf.textContent=mon.def}
function bdg(ev){if(acs.has(ev))return;acs.add(ev);ach(ev).then(a=>{let b=document.createElement('span');b.className='badge';b.textContent=a.nm;el.ach.appendChild(b);sys(`Achievement: ${a.nm} — ${a.ds}`)})}
function end(v){let a=tot>0?(crt/tot*100).toFixed(1):0;el.nar.textContent=v?`🎉 CONGRATULATIONS! You've conquered the ${sub} dungeon! 🎉`:`💀 Defeated... The ${sub} dungeon proved too difficult.`;sys(v?'🎉 VICTORY!':'💀 DEFEAT');sys(`Quiz Complete! Correct: ${crt}/${tot} (${a}%)`);sys(`Final Stats - Level: ${plr.lvl} · Gold: ${plr.gld} · XP: ${plr.xp} · Best Streak: ${plr.str}`);sav();el.nxt.disabled=0}
async function ent(){if(el.go.disabled)return;el.go.disabled=1;try{cls(el.men,'hid',1);cls(el.lod,'hid',0);let k=el.key.value.trim();if(k)key=k;dm=el.dem.checked;stg=0;rst();sys('🏰 Entering '+sub+' dungeon...');ctx=await nar('entry');el.nar.textContent=ctx;cls(el.lod,'hid',1);cls(el.bat,'hid',0);spn();await say('spawn');await nxt()}catch(e){sys('❌ '+e.message);cls(el.lod,'hid',1);cls(el.men,'hid',0)}el.go.disabled=0}
async function say(e){let t=await nar(e);if(t)el.nar.textContent=t}
async function nxt(){if(plr.hp<=0)return sys('⚠️ Player defeated');if(el.nxt.disabled)el.nxt.disabled=0;el.nxt.disabled=1;el.qp.textContent='🔄 Loading...';el.opt.innerHTML='';try{let j=await gq();if(!j?.q||!j.opt||j.opt.length!==4||typeof j.ans!=='number'||j.ans<0||j.ans>3)throw Error('Invalid question');qst=j;tot++;el.qp.textContent=j.q;el.opt.innerHTML='';j.opt.forEach((o,i)=>{let b=document.createElement('button');b.innerHTML=`<b>${'ABCD'[i]}.</b> <span>${o}</span>`;b.onclick=()=>ans(i,b);el.opt.appendChild(b)});adp();sys('📝 Q'+(tot)+' loaded')}catch(e){sys('❌ '+e.message);el.qp.textContent='⚠️ Failed. Retry.';el.nxt.disabled=0}}
async function ans(i,b){if(!el.nxt.disabled)return;[...el.opt.children].forEach(x=>x.disabled=1);if(qst.ans===undefined)return sys('❌ Corrupted');let c=qst.ans===i;sys('💭 "'+qst.opt[i]+'"');if(c){crt++;plr.str++;sys('✅ Correct!');if(plr.str===5)bdg('str5');if(plr.str===3)bdg('hot');let d=pdm();mon.hp=Math.max(0,mon.hp-d);msg(`⚔️ You strike ${d} dmg! (${plr.str}x streak)`);b.classList.add('correct');if(mon.hp<=0){win++;let g=rnd(10,20),x=150;plr.gld+=g;plr.xp+=x;lvc();upd();sys(`🏆 ${mon.nm} defeated! +${g}💰 +${x}✨XP`);bdg(stg%4===3?'boss':'win');await say('win');stg++;if(stg>=4){sys('🎉 DUNGEON CLEARED!');end(1);return}spn();await say('spawn');await nxt();return}}else{sys('❌ Correct was: "'+qst.opt[qst.ans]+'"');plr.str=0;let d=mdm();plr.hp=Math.max(0,plr.hp-d);msg(`💥 ${mon.nm} hits you for ${d} damage!`);b.classList.add('wrong');let t=await tnt('wrong');sys('🗣️ '+mon.nm+': "'+t+'"');let exp=qst.exp||'Review this concept to improve.';if(!dm){try{let prm=`For question "${qst.q}", explain clearly and educationally why "${qst.opt[qst.ans]}" is correct. Also explain why "${qst.opt[i]}" is wrong. Max 60 words. Be helpful and encouraging.`;exp=(await aic(prm,150,.6)).trim()}catch(e){}}sys('💡 Explanation: '+exp);if(plr.hp<=0){plr.hp=0;upd();sys('💀 DEFEATED');await say('lose');end(0);return}}upd();el.nxt.disabled=0}
async function nxb(){if(mon.hp>0&&plr.hp>0)await nxt()}
$$('.dng').forEach(b=>b.onclick=()=>{$$('.dng').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');sub=b.dataset.sub});
el.go.onclick=ent;el.nxt.onclick=nxb;el.clr.onclick=()=>{localStorage.clear();location.reload()};el.key.addEventListener('input',e=>key=e.target.value.trim());
$$('.dng')[0].classList.add('sel');sys('Correct=Damage, Wrong=HP loss');sys('5-streak=Achievement');window.plr=plr;window.mon=mon;window.qst=qst})();
